### PR TITLE
Remove superflous AddInContextSizes

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
It is brittlely duplicative with the existing accessors

---
This change is [Reviewable](https://reviewable.io/reviews/sherm1/drake/4)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
Oh, does this actually work for nested diagrams? I guess it depends on sub-diagrams to have already been completed prior to adding them into super-diagrams. My implementation depended only on LeafSystems being complete. Is it always safe to assume the subdiagrams are done? That does seem reasonable for DiagramBuilder productions. How about systems produced by transmogrification?

> *[Reviewable](https://reviewable.io/reviews/sherm1/drake/4#-:-M0tPt1Y8_d1disKeXsw:b-xoghbh)* status: 0 of 6 files reviewed, all discussions resolved

**Comment by jwnimmer-tri** [comment]
I believe the contract of Systems added to a Diagram is that they are fully-formed when added and invariant afterward.  We should be able to count on Initialize having completed before anyone tries to use a Diagram.

**Comment by sherm1** [comment]
My first read of Diagram::ConvertScalarType() [here](https://github.com/RobotLocomotion/drake/blob/master/systems/framework/diagram.h#L1322) suggests that it does _not_ call Initialize() on sub-Diagrams. In that case the non-recursive approach would fail without some fix that would copy the ContextSize stuff.

Clearly I need to add a post-transmog unit test to make sure the counts are still correct!

**Comment by jwnimmer-tri** [comment]
The call to `get_system_scalar_converter().Convert()` must return a well-behaved System.  Indeed, the call to `other.ConvertScalarType` ([here](https://github.com/RobotLocomotion/drake/blob/7ba9b22595a2a1cd863d9d0058187787ec0d4068/systems/framework/diagram.h#L1457-L1459)) returns a blueprint which is passed to the constructor ([here](https://github.com/RobotLocomotion/drake/blob/7ba9b22595a2a1cd863d9d0058187787ec0d4068/systems/framework/diagram.h#L1457-L1459)) which does call `Initialize`.

**Review by sherm1 — COMMENTED** [review]
Wow -- that was hard to trace! I gave up on code archaeology and used the debugger to see that Convert eventually makes a call to that constructor. Looks safe -- I'll switch.

> *[Reviewable](https://reviewable.io/reviews/sherm1/drake/4#-:-M0tq33vC2HlxL8xhc6a:b-hs0uo7)* status: 0 of 6 files reviewed, all discussions resolved

**Pull request closed without merging**
