### PR TITLE
Remove useless code

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/sherm1/drake/2)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Note that this breaks the System and Port unit tests (they are testing the removed APIs), but the LcmSystem's unit test still passes.

**Comment by jwnimmer-tri** [comment]
This is ready now -- passes all tests locally (except for the cpplint that's broken on the original branch).

**Comment by sherm1** [comment]
Thanks @jwnimmer-tri, I get it now! I'm happy to see all that code go away.

---

Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sherm1/drake/2#-:-Km-GiakLx_xfl6en0Zs:b-xik1g)*

**Comment by jwnimmer-tri** [comment]
This has been manually merged.  Thanks!

**Pull request closed without merging**
